# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_joint_trajectory_controller
    - right_joint_trajectory_controller
    - left_gripper_controller
    - right_gripper_controller

  left_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - robl_joint_1
      - robl_joint_2
      - robl_joint_3
      - robl_joint_4
      - robl_joint_5
      - robl_joint_6
      - robl_joint_7
  right_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - robr_joint_1
      - robr_joint_2
      - robr_joint_3
      - robr_joint_4
      - robr_joint_5
      - robr_joint_6
      - robr_joint_7
  left_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - grpl_half_aperture_joint
  right_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - grpr_half_aperture_joint