# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    yumi_arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

yumi_arms_controller:
  ros__parameters:
    joints:
      - robl_joint_1
      - robl_joint_2
      - robl_joint_3
      - robl_joint_4
      - robl_joint_5
      - robl_joint_6
      - robl_joint_7
      - robr_joint_1
      - robr_joint_2
      - robr_joint_3
      - robr_joint_4
      - robr_joint_5
      - robr_joint_6
      - robr_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true